### ISSUE TITLE
PDC Layer Display

### ISSUE THREAD

**Issue by Happs80** [thinkWhere/DMIS#109]
I think listing all the PDC hazard icons looks a bit odd. Users can click on the icon for more information if required.

Can we just show one icon as 'representative' of the others (perhaps the fire icon?).

Also, on Basecamp on 15 Aug, I asked if we could display the following properties. Is it possible to display as requested?

**James 
In terms of the properties to display for PDC alerts, please show the following:
- Name
- Type
- Severity
- Last Update
- Lat
- Lon
- Severity_ID

Thank you.
Posted on Aug 15**

**Comment by dcfrankland** [comment]
Hi @LindaAlblas - could we action this please as per James's description i.e. only show one indicative PDC icon rather than all of them.

**Comment by LindaAlblas** [comment]
Hi @Happs80 , only one legend item is now shown for the PDC layer. The legend is coming from a PDC's ArcGIS REST API we don't have control over, which is why 'avalance' (first item) is shown and not 'fire'. I have had to change to code to ignore any other legend items so this means that if there are any more ArcGIS REST layers in the future, that it will only show the first legend item for them too.
