### ISSUE TITLE
Evacuation Site Icon

### ISSUE THREAD

**Issue by Happs80** [thinkWhere/DMIS#111]
Is it possible to change the evacuation icon to this: http://cdn.mysitemyway.com/icons-watermarks/simple-black/iconathon/iconathon_evacuation-point/iconathon_evacuation-point_simple-black_512x512.png

**Comment by st-mpc** [comment]
Icon for evacation stored on s3 rather than geoserver store:
https://s3-eu-west-1.amazonaws.com/tw-dmis/icons/evacuation-point_black_512x512.png

Geosever SLD changed to reference external resource:

 <Graphic>
              <ExternalGraphic>
                <onlineResource xlink:href="https://s3-eu-west-1.amazonaws.com/tw-dmis/icons/evacuation-point_black_512x512.png" />
                <Format>image/png</Format>
              </ExternalGraphic>
              <Size>14</Size>
            </Graphic>

Any thoughts on size? - I have made this slightly bigger than the original size 10. 

Martin

**Comment by popelnuh** [comment]
pd-85

**Comment by popelnuh** [comment]
The icon has been updated.
